In [1]:
import numpy as np
import cv2
import os

In [2]:
img = np.zeros((3, 3), dtype=np.uint8)
print(img)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [3]:
img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
print(img)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [4]:
img.shape

(3, 3, 3)

In [5]:
image = cv2.imread('c:/users/macbookair/pictures/hi.jpg')

In [6]:
#cv2.imshow('image', image)

In [7]:
cv2.imwrite('mypic.png', image)

True

In [8]:
grayImage = cv2.imread('mypic.png', cv2.IMREAD_GRAYSCALE)

In [9]:
cv2.imwrite('mypic_gray.png', grayImage)

True

In [10]:
#cv2.imshow('mypic_gray', grayImage)

In [11]:
#利用随机生成的字节数生成黑白和RGB图片
randomByteArray = bytearray(os.urandom(120000))
flatNumpyArray = np.array(randomByteArray)

grayImage = flatNumpyArray.reshape(300, 400)
cv2.imwrite('RandomGray.png', grayImage)

bgrImage = flatNumpyArray.reshape(100, 400, 3)
cv2.imwrite('RandomBgr.png', bgrImage)

True

In [12]:
#利用numpy数组生成随机数 产生图片
grayImage_ = np.random.randint(0, 256, 120000).reshape(300, 400)
cv2.imwrite('grayImage_.jpg', grayImage_)

bgrImage_ = np.random.randint(0, 256, 360000).reshape(300, 400, 3)
cv2.imwrite('bgrImage_.jpg', bgrImage_)

True

In [13]:
img_1 = cv2.imread('bgrImage_.jpg')
img_1[100:200, 100:200] = [0, 255, 255] #改变特定区域的值 变为黄色
#cv2.imshow('img_1', img_1)
img_1[:,:,1] = 0  #改变通道的值 
cv2.imwrite('img_1.jpg', img_1)

True

In [14]:
#图像的内部复制
mypic = cv2.imread('mypic.png')
funny_area = mypic[100:200, 100:200,:]
mypic[0:100, 0:100, :] = funny_area
cv2.imwrite('mypic_copy.png', mypic)

True

In [15]:
print(mypic.shape)

(453, 450, 3)


In [16]:
print(mypic.size)

611550


In [17]:
print(mypic.dtype)

uint8


In [18]:
#显示图片
cv2.imshow('my image', mypic)
cv2.waitKey()
cv2.destroyAllWindows()

In [5]:
img_1 = cv2.imread('img_1.png')
cv2.imshow('img_1', img_1)
cv2.waitKey()
cv2.destroyAllWindows()
print(img_1[0, 0])

[117 143 116]


In [2]:
#视频文件的读、写
videoCapture = cv2.VideoCapture('conv.avi')
fps = videoCapture.get(cv2.CAP_PROP_FPS)
size = (int(videoCapture.get(cv2.CAP_PROP_FRAME_WIDTH)), 
        int(videoCapture.get(cv2.CAP_PROP_FRAME_HEIGHT)))
videoWrite = cv2.VideoWriter('MyOutputVideo.avi', cv2.VideoWriter_fourcc('X', 'V', 'I', 'D'), fps, size)

success, frame = videoCapture.read()
while success:
    videoWrite.write(frame)
    success, frame = videoCapture.read()

In [11]:
cameraCapture = cv2.VideoCapture(0)
fps = 30
size = (int(cameraCapture.get(cv2.CAP_PROP_FRAME_WIDTH)),int(cameraCapture.get(cv2.CAP_PROP_FRAME_HEIGHT)))
videoWrite = cv2.VideoWriter('MyOutCameVideo.avi', cv2.VideoWriter_fourcc('X', 'V', 'I', 'D'), fps, size)
success, frame = cameraCapture.read()
numFramesRemaining = 10 * fps - 1
while success and numFramesRemaining > 0:
    videoWrite.write(frame)
    success, frame = cameraCapture.read()
    numFramesRemaining -= 1
cameraCapture.release()

In [ ]:
#在窗口显示摄像头帧
clicked = False
def onMouse(event, x, y, flag, param):
    global clicked
    if event == cv2.EVENT_LBUTTONUP:
        clicked = True
        
cv2.namedWindow('My camera video')
cv2.setMouseCallback('My camera video', onMouse)
print('Showing camera feed.click window or press any key to stop!')
cameraCapture = cv2.VideoCapture(0)
success, frame = cameraCapture.read()

while success and cv2.waitKey(1) == -1  and not clicked:
    cv2.imshow('My camera video', frame)
    success, frame = cameraCapture.read()
cv2.destroyWindow('My camera video')
cameraCapture.release()

Showing camera feed.click window or press any key to stop!


12